[package]
name = "guidemaker-scan"
version = "0.1.0"
edition = "2021"

[lib]
name = "guidemaker_scan"
path = "src/lib.rs"

[[bin]]
name = "guidemaker-scan"
path = "src/main.rs"

[[bin]]
name = "guidemaker-step2"
path = "src/bin/step2.rs"

[[bin]]
name = "guidemaker-step3"
path = "src/bin/step3.rs"

[dependencies]
bio = "4.0"
polars = { version = "0.43.0", features = ["csv", "parquet", "dtype-categorical", "lazy"] }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
libc = "0.2"
hashbrown = { version = "0.14.5", features = ["raw"] }
flate2 = "1.0"
zstd = "0.13"
rayon = "1.10"

[dev-dependencies]
tempfile = "3"
