site_name: GuideMaker Documentation
site_url: https://guidemaker.org  # <-- ADD THIS LINE

theme:
  name: material

plugins:
  - search
  - include-markdown:
      opening_tag: "{%"
      closing_tag: "%}"
      comments: false
  - mkdocstrings:
      handlers:
        python:
          paths: [.]

nav:
  - Home: index.md
  - API Reference: api.md
