site_name: GuideMaker Documentation
theme:
  name: material

plugins:
  - search
  - include-markdown:
      opening_tag: "{%"
      closing_tag: "%}"
      comments: false
  - mkdocstrings:
      handlers:
        python:
          paths: [.]

nav:
  - Home: index.md
  - API Reference: api.md

# Add this to preserve your custom domain name:
extra:
  cname: guidemaker.org
